# Generated by Django 6.0.3 on 2026-03-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_value", models.CharField(db_index=True, max_length=512)),
                ("indicator_type", models.CharField(max_length=32)),
                ("verdict", models.CharField(max_length=32)),
                ("verdict_confidence", models.IntegerField(default=0)),
                ("query_time_seconds", models.FloatField(default=0.0)),
                ("sources_queried", models.IntegerField(default=0)),
                ("sources_errored", models.IntegerField(default=0)),
                (
                    "resolved_ip",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "resolved_hostname",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("report_json", models.TextField(help_text="Full report as JSON")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
